### ISSUE TITLE
iOS version compatible with 64 bits

### ISSUE THREAD

**Issue by jmsalvadortwonav** [openalias/dnscrypt-python#2]
I sent you an email few weeks ago asking you about a new iOS release compatible with 64 bits of your library.

This is due to Apple force the iOS apps that must be compatible with 64 bits before 1st of June.

Would you release a 64 bits compatible version of iOS before 1st of June ?

Please, tell me something about the compatibility of your library in order to have a reaction and be compatible in that date. Time is running fast.

Thanks in advance
Josep-Miquel

**Comment by fluffypony** [comment]
@soulianisrahm hi - I haven't seen any emails come in about that, did you send it to dev@openalias.org?

Either way, I don't think that bitwise compatibility is an issue with this python library, but I stand to be corrected.

**Comment by jmsalvadortwonav** [comment]
I sent the mails to contact in www.pureftpd.org

I didn't know exactly where to send it

sorry for the inconvenience

El 04/05/2015 a las 15:51, Riccardo Spagni escribió:

> @soulianisrahm https://github.com/soulianisrahm hi - I haven't seen 
> any emails come in about that, did you send it to dev@openalias.org 
> mailto:dev@openalias.org?
> 
> Either way, I don't think that bitwise compatibility is an issue with 
> this python library, but I stand to be corrected.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openalias/dnscrypt-python/issues/2#issuecomment-98709524.

## 

_Josep-Miquel Salvador_
Technical Department

tel.: 902512260
int. tel.: +34 933968068
fax: +34 937959605
skype: josep.miquel.salvador
email: jmsalvador@compegps.com mailto:jmsalvador@compegps.com

www.compegps.com http://www.compegps.com
www.twonav.com http://www.twonav.com

CompeGPS Team SL
Carrer d'en Draper, 13
08350 Arenys de Mar
Barcelona - Spain

UTM 31T X 461512 Y 4603162
(WGS 84)

Este e-mail contiene información confidencial, el contenido de la misma 
se encuentra protegido por Ley. Cualquier persona distinta a su 
destinataria tiene prohibida su reproducción, uso, divulgación o 
impresión total o parcial. Si ha recibido este mensaje por error, 
notifíquelo de inmediato al remitente borrando el mensaje original 
juntamente con sus ficheros anexos.

Aquest correu electrònic conté informació confidencial, el contingut del 
mateix es troba protegit per Llei Qualsevol persona que no sigui el seu 
destinatari té prohibida la seva reproducció, ús, divulgació o impressió 
total o parcial. Si ha rebut aquest missatge per error, notifiqui-ho 
immediatament al remitent esborrant el missatge original juntament amb 
els seus fitxers adjunts.

This e-mail contains confidential information, its content is protected 
by Law. Any person other than the addressee has no right to reproduce, 
use, disclosure or print any part of this e-mail. If you have received 
this message by accident, please notify this fact to the sender and 
delete the original message as well as its attachments.

Ce message contient des informations confidentielles, le contenu de 
celui-ci est protégé par la loi. Il est établi à l'intention exclusive 
de ses destinataires. Toute divulgation, utilisation, diffusion ou 
reproduction (totale ou partielle) de ce message, ou des informations 
qu'il contient, doit être préalablement autorisée. Si vous n'êtes pas 
destinataire de ce message, merci de le détruire immédiatement et 
d'avertir l'expéditeur de l'erreur de distribution et de la destruction 
du message

**Comment by fluffypony** [comment]
Oh that's for dnscrypt-proxy: https://github.com/jedisct1/dnscrypt-proxy - this is dnscrypt-python :)
